# Project information
site_name: QgisModelBaker
site_description: >-
  This site contains documentation about QGIS Model Baker

# Repository
repo_name: opengisch/QgisModelBaker
repo_url: https://github.com/opengisch/QgisModelBaker
edit_uri: https://github.com/opengisch/QgisModelBaker/tree/master/docs/

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs

# Page tree
nav:
  - Home: index.md
  - Installation & maintenance (en): installation.md
  - Development (en): development.md

markdown_extensions:
  - attr_list
  - def_list
  - admonition
